name: iOS Release

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Release track'
        required: true
        type: choice
        options:
          - testflight
          - appstore

jobs:
  release-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build iOS
        run: flutter build ipa --release
      
      - name: Setup fastlane
        run: |
          cd ios
          bundle install
      
      - name: Upload to TestFlight
        if: inputs.track == 'testflight'
        run: |
          cd ios
          bundle exec fastlane beta
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_ASP }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      - name: Upload to App Store
        if: inputs.track == 'appstore'
        run: |
          cd ios
          bundle exec fastlane release
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_ASP }}
      
      - name: Notify on success
        if: success()
        run: echo "✅ iOS release to ${{ inputs.track }} successful"
      
      - name: Notify on failure
        if: failure()
        run: echo "❌ iOS release failed"
